version: '3.8'

# postgres:16.3-alpine

services:
  solidapi:
    image: bitnami/postgresql
    container_name: apisolid
    restart: always
    environment:
      POSTGRESQL_USERNAME: docker
      POSTGRESQL_PASSWORD: docker
      POSTGRESQL_DATABASE: solid
    ports:
      - 5434:5432
    # volumes:
    #   - ./data/postgres:/var/lib/postgresql/data